version: "3.7"

services:
  neo4j:
    image: neo4j
    container_name: neo4j
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_AUTH=neo4j/10122000

    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    restart: unless-stopped


  web-service:
    build: /web-service
    restart: always
    depends_on:
      - neo4j
    ports:
      - "5000:5000"
